config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  ActiveAdmin.routes(self)
  mount_devise_token_auth_for "User", at: "auth"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :guest_sessions
      resources :facebook_sessions
      namespace :my do
        resources :queries
        resources :conversations
      end
    end
  end

  resources :messages
  resources :conversations

  resources :password_reset_requests
  resources :recommend_keywords
  resources :contents
  resources :categories
  namespace :excel do
    resources :recommend_keywords
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :session_signin
  get '/signout' => 'sessions#destroy', :as => :session_signout
  get '/auth/failure' => 'sessions#failure'
end

app/controllers/api/v1/my/conversations_controller.rb
module Api::V1
  module My
    class ConversationsController < ApplicationController
      before_action :authenticate_user!
      before_filter :get_mailbox, :get_box, :get_actor
      before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]

      def index
        @conversations = @mailbox.conversations
        render json: @conversations, each_serializer: ConversationsSerializer
      end

      def show
        @receipts = @mailbox.receipts_for(@conversation).not_trash
        render json: @receipts, each_serializer: ReceiptsSerializer
        @receipts.mark_as_read
      end

      def create
        staffs = User.member.where(role: 'admin', provider: 'session')
        staffs.each do |staff|
          @actor.send_message(staff, params[:body], params[:subject])
        end

        render json: @mailbox.conversations, each_serializer: ConversationsSerializer
      end

      def update
        last_receipt = @mailbox.receipts_for(@conversation).last
        @receipt = @actor.reply_to_all(last_receipt, params[:body])
        @receipts = @mailbox.receipts_for(@conversation).not_trash
        render json: @receipts, each_serializer: ReceiptsSerializer
        @receipts.mark_as_read
      end

      def destroy

        @conversation.move_to_trash(@actor)

        respond_to do |format|
          format.html {
            if params[:location].present? and params[:location] == 'conversation'
              redirect_to conversations_path(:box => :trash)
    	else
              redirect_to conversations_path(:box => @box,:page => params[:page])
    	end
          }
          format.js {
            if params[:location].present? and params[:location] == 'conversation'
              render :js => "window.location = '#{conversations_path(:box => @box,:page => params[:page])}';"
    	else
              render 'conversations/destroy'
    	end
          }
        end
      end

      private

      def get_mailbox
        @mailbox = current_user.mailbox
      end

      def get_actor
        @actor = current_user
      end

      def get_box
        if params[:box].blank? or !["inbox","sentbox","trash"].include? params[:box]
          params[:box] = 'inbox'
        end

        @box = params[:box]
      end

      def check_current_subject_in_conversation
        @conversation = @mailbox.conversations.find_by_id(params[:id])

        if @conversation.nil? or !@conversation.is_participant?(@actor)
          redirect_to conversations_path(:box => @box)
        return
        end
      end

    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_manager!
  before_filter :get_mailbox, :get_box, :get_actor
  before_filter :check_current_subject_in_conversation, :only => [:show, :update, :destroy]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox.page(params[:page]).per(9)
    elsif @box.eql? "sentbox"
      @conversations = @mailbox.sentbox.page(params[:page]).per(9)
    else
      @conversations = @mailbox.trash.page(params[:page]).per(9)
    end

    respond_to do |format|
      format.html { render partial: 'conversation', collection: @conversations if request.xhr? }
    end
  end

  def show
    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    render :action => :show
    @receipts.mark_as_read
  end

  def update
    if params[:untrash].present?
    @conversation.untrash(@actor)
    end

    if params[:reply_all].present?
      last_receipt = @mailbox.receipts_for(@conversation).last
      @receipt = @actor.reply_to_all(last_receipt, params[:body])
    end

    if @box.eql? 'trash'
      @receipts = @mailbox.receipts_for(@conversation).trash
    else
      @receipts = @mailbox.receipts_for(@conversation).not_trash
    end
    redirect_to :action => :show
    @receipts.mark_as_read

  end

  def destroy

    @conversation.move_to_trash(@actor)

    respond_to do |format|
      format.html {
        if params[:location].present? and params[:location] == 'conversation'
          redirect_to conversations_path(:box => :trash)
	else
          redirect_to conversations_path(:box => @box,:page => params[:page])
	end
      }
      format.js {
        if params[:location].present? and params[:location] == 'conversation'
          render :js => "window.location = '#{conversations_path(:box => @box,:page => params[:page])}';"
	else
          render 'conversations/destroy'
	end
      }
    end
  end

  private

  def get_mailbox
    @mailbox = current_manager.mailbox
  end

  def get_actor
    @actor = current_manager
  end

  def get_box
    if params[:box].blank? or !["inbox","sentbox","trash"].include?params[:box]
      params[:box] = 'inbox'
    end

    @box = params[:box]
  end

  def check_current_subject_in_conversation
    @conversation = @mailbox.conversations.find_by_id(params[:id])

    if @conversation.nil? or !@conversation.is_participant?(@actor)
      redirect_to conversations_path(:box => @box)
    return
    end
  end

end

app/views/conversations/_conversation.html.erb
<%= div_for(conversation, :class =>"card") do %>
  <% if conversation.is_unread?(@actor) %>
    <div class="content_left card-header unread card-inverse" style='background-color: #faf2cc; border-color: #faf2cc;'>
  <% else %>
    <div class="content_left card-header">
  <% end %>
    <div class="card-title">
      <%= link_to conversation.last_sender.name, admin_user_path(conversation.last_sender) %>
    </div>
    <h4 class="subject card-text">
      <%= link_to(truncate(conversation.subject, :length => 55), conversation_path(conversation.id,:box => @box,:page => params[:page])) %>
    </h4>
    <div class="date card-subtitle">
      <%= "#{time_ago_in_words(conversation.updated_at)} 전" %>
    </div>
  </div>
  <div class="card-block">
    <div class="briefing card-text">
      <%= raw(truncate(strip_tags(conversation.last_message.body), :length => 50)) %>
    </div>
    <% unless @box.eql?'trash' %>
      <div class="action card-link">
        <%= link_to('휴지통으로', conversation_path(conversation, :location => @box,
                                                    :box => @box,
                                                    :page => params[:page]),
                                                    :confirm => '삭제하시겠습니까',
                                                    :method => :delete) %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/conversations/_conversation_full.html.erb
<div class='col-sm-9 col-md-10 '>
  <h3>
    <%= conversation.subject %>
  </h3>
  <h4>
    대화 참여자:
  </h4>
  <div class="participants">
    <% conversation.recipients.each do |recp| %>
      <%= link_to recp.name, admin_user_path(recp) %>
    <% end %>
  </div>
  <div class="action">
    <% unless @box.eql?'trash' %>
      <%= link_to('대화 휴지통으로', conversation_path(conversation, :location => 'conversation', :box => @box),
             :confirm => '삭제하시겠습니까?',
             :method => :delete, :remote => true) %>
    <% end %>
  </div>
  <hr class="soften">
  <div class="messages">
    <% @receipts.each do |receipt| %>
      <%= render 'messages/message', message: receipt.message %>
    <% end %>

    <% unless @box.eql?'trash' %>
    <br>
    <%= form_tag conversation_path(conversation), :method => :put, :class => "cont_conversation" do %>
    <% if @receipt and @receipt.errors.any? %>
      <div class="error">
        <h2>
          <%= pluralize(@receipt.errors.count, "error") %> prohibited this message from being sent:
        </h2>
        <ul>
          <% @receipt.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="editor">
      <%= text_area_tag :body, nil, :rows =>6, :cols => 53, :class => "required form_tag" %>
    </div>
    <div class="actions">
      <%= submit_tag '답장 보내기', :name => :reply_all, :class => "btn" %>
    </div>
    <% end %>
    <%end %>
  </div>

  <%= javascript_tag do %>
  $(document).ready(function(){
    $(".message .body img").each(function(){
      var link = '<a href=\"' + $(this).attr('src') + '\" class=\"img_link\"><img src=\"' + $(this).attr('src') + '\"></a>';
      $(this).after(link);
      $(this).remove();
      $(".message .body img").aeImageResize({ height: 490, width: 490 });
      $(".message .body a.img_link").lightBox({
        maxHeight: 920,
        maxWidth: 920,
        imageLoading: '../assets/lightbox-ico-loading.gif',
        imageBtnClose: '../assets/lightbox-btn-close.gif',
        imageBtnPrev: '../assets/lightbox-btn-prev.gif',
        imageBtnNext: '../assets/lightbox-btn-next.gif',
        imageBlank: '../assets/lightbox-blank.gif'
      });
    })
  });
  <% end %>
</div>

app/views/conversations/_index.html.erb
<div class="col-sm-9 col-md-10 main conversations">
  <%= render partial: 'conversation', collection: @conversations %>

  <%= render partial: 'layouts/more',
             locals: {
               path: conversations_path,
               per_page: 9,
               total: @conversations.total_count
            } %>
</div>

app/views/conversations/_show.html.erb
<div class="conversation_full">
  <%= render partial: 'conversation_full', locals: { conversation: @conversation } %>
</div>

app/views/conversations/destroy.js.erb
$('#conversation_<%= @conversation.id %>').remove();

app/views/conversations/edit.html.erb
<% content_for :title do %>
  <%=t('message.other')%>
<% end %>

<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/conversations/index.html.erb
<section id="conversations row">

  <%= render partial: 'toolbar/messages' %>

  <%= render :partial => 'index' %>

  <%= javascript_tag do %>
    $(function() {
      SocialStream.Conversation.index();
    });
  <% end %>

</section>

app/views/conversations/index.js.erb
$("#content").html("<%=escape_javascript(render :partial => 'index') %>");
<%= location(link_to(image_tag("btn/message_" + @box + ".png", :class => "menu_icon")+t('message.' + @box), conversations_path(:box => @box),:remote => true)) %>

$('.pagination a').attr('data-remote', 'true');
	  
<%= toolbar :messages %>

app/views/conversations/show.html.erb
<% content_for :title do %>
  <%= "메세지 보기" %>
<% end %>

<section id="conversation">
  <%= render partial: 'toolbar/messages' %>
  <%= render :partial => 'show' %>
  <%= javascript_tag do %>
$('.cont_conversation').validate({errorClass: "validation_error"});
<% unless @box.eql?'trash' %>
  $("#body").cleditor({
    width:493
  });

		var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash.length > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});
		}
<% else %>
		var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
		if (message_hash && message_hash > 0){
			$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
		}else{
			$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});
		}
<% end %>
<% end %>
</section>

app/views/conversations/show.js.erb
$("#content").html("<%= escape_javascript(render :partial => 'show') %>");

<%= toolbar :messages %>

$('.cont_conversation').validate({errorClass: "validation_error"});
<% unless @box.eql?'trash' %>
  $("#body").cleditor({
    width:493,
    controls:  "<%= SocialStream.cleditor_controls %>"     
  });

	var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
	if (message_hash && message_hash.length > 0){
		$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
	}else{
		$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
	}

<% else %>
	var message_hash = window.location.hash.match(/^.*message_(\d+).*$/);
	if (message_hash && message_hash.length > 0){
		$.scrollTo('#message_' + message_hash[1] ,1500,{axis:'y'});
	}else{
		$.scrollTo('#message_<%= @conversation.last_message.id %>',1500,{axis:'y'});		
	}
<% end %>