config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  ActiveAdmin.routes(self)
  mount_devise_token_auth_for "User", at: "auth"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :guest_sessions
      resources :facebook_sessions
      namespace :my do
        resources :queries
        resources :conversations
      end
    end
  end

  resources :messages
  resources :conversations

  resources :password_reset_requests
  resources :recommend_keywords
  resources :contents
  resources :categories
  namespace :excel do
    resources :recommend_keywords
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :session_signin
  get '/signout' => 'sessions#destroy', :as => :session_signout
  get '/auth/failure' => 'sessions#failure'
end

app/views/layouts/_loading.html.erb
<article class="loading">
  <div class="progress progress-striped active">
    <div class="bar" style="width: 100%">
    </div>
  </div>
</article>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_more.html.erb
<% if (remaining = total - per_page) > 0 %>
<nav class="more">
  <%= link_to '더보기', "#", "data-path" => path, "data-remaining" => remaining, "data-per_page" => per_page %>

  <%= render partial: 'layouts/loading' %>
</nav>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if manager_signed_in? %>
  <li class='nav-item'><%= link_to 'Sign out', session_signout_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '관리자메뉴', admin_root_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '고객 문의 관리', conversations_path, class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', session_signin_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Goguma", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%#= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Goguma" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Goguma" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container-fluid">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>